name: Deploy Lambda to AWS

on:
  push:
    branches: [master]  # o "main" si usas otra rama

env:
  AWS_REGION: us-east-1
  STACK_NAME: order-function-stack
  LAMBDA_PACKAGE_KEY: order_function.zip

  # IDs del API Gateway existente (puedes moverlos a GitHub Secrets o `action.yaml`)
  REST_API_ID: ${{ secrets.REST_API_ID }}
  ORDER_RESOURCE_ID: ${{ secrets.ORDER_RESOURCE_ID }}
  ROOT_RESOURCE_ID: ${{ secrets.ROOT_RESOURCE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publicar Lambda
        run: dotnet publish ./app/src/AWSLambda/AWSLambda.csproj -c Release -o ./publish

      - name: Crear ZIP de Lambda
        run: |
          cd publish
          zip -r ../$LAMBDA_PACKAGE_KEY .
          cd ..

      - name: Instalar AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Obtener nombre del bucket creado por la plantilla (si ya existe el stack)
        id: getbucket
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='LambdaBucketName'].OutputValue" \
            --output text || echo "")
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          if [ -z "$BUCKET_NAME" ]; then
            echo "❌ No se encontró un bucket creado. Se usará el nombre esperado por la plantilla."
            echo "BUCKET_NAME=order-function-deploy-${{ secrets.AWS_ACCOUNT_ID }}-${{ env.AWS_REGION }}" >> $GITHUB_ENV
          fi

      - name: Subir ZIP a S3
        run: |
          aws s3 cp $LAMBDA_PACKAGE_KEY s3://$BUCKET_NAME/$LAMBDA_PACKAGE_KEY

      - name: Desplegar CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/template.yaml \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              LambdaS3Key=$LAMBDA_PACKAGE_KEY \
              RestApiId=$REST_API_ID \
              OrderResourceId=$ORDER_RESOURCE_ID \
              RootResourceId=$ROOT_RESOURCE_ID
